sudo: false
 
language: node_js

node_js:
  - "7"
 
before_install:
  - npm install -g angular-cli
  # - curl https://install.meteor.com | /bin/sh
  # - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
  - graphqlServer/node_modules
  - webApp/node_modules
 
before_script:
  - cd graphqlServer
  # - meteor update --packages-only
  - npm install
  - cd ../webApp
  - npm install

script:
  - npm run build
  # - meteor build $HOME/build.tgz